# Generated by Django 5.1.5 on 2025-02-15 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coordinator', '0003_alter_coordinator_status'),
        ('Counsellor', '0003_alter_counsellor_status'),
        ('Student', '0005_alter_student_status'),
        ('nexus', '0009_alter_batch_batch_time_alter_batch_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feesrecords',
            name='counsellor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Counsellor.counsellor'),
        ),
        migrations.AlterField(
            model_name='student',
            name='course_counsellor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Counsellor.counsellor'),
        ),
        migrations.AlterField(
            model_name='student',
            name='location',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nexus.location'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_assing_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_assing', to='Coordinator.coordinator'),
        ),
        migrations.AlterField(
            model_name='student',
            name='support_coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Coordinator.coordinator'),
        ),
    ]
