# Generated by Django 5.1.5 on 2025-02-15 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0006_alter_feesrecords_counsellor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mode',
            field=models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline'), ('Hybrid', 'Hybrid')], max_length=10),
        ),
    ]
