# Generated by Django 5.1.5 on 2025-02-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0007_alter_student_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcourse',
            name='certificate_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
