# Generated by Django 5.1.5 on 2025-03-08 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0009_studentcourse_student_certificate_allotment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='preferred_week',
            field=models.CharField(choices=[('Weekdays', 'Weekdays'), ('Weekends', 'Weekends'), ('Hybrid', '    ')], max_length=10),
        ),
    ]
