# Generated by Django 5.1.5 on 2025-03-11 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0010_alter_student_preferred_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
