# Generated by Django 5.1.5 on 2025-03-16 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0011_alter_student_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='preferred_week',
            field=models.CharField(choices=[('Weekdays', 'Weekdays'), ('Weekends', 'Weekends'), ('Both', 'Both')], max_length=10),
        ),
    ]
