# Generated by Django 5.1.5 on 2025-03-25 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0012_alter_student_preferred_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcourse',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('denied', 'Denied')], default='not_started', max_length=20),
        ),
    ]
