# Generated by Django 5.1.5 on 2025-03-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0013_alter_studentcourse_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcourse',
            name='status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Denied', 'Denied')], default='not_started', max_length=20),
        ),
    ]
