# Generated by Django 5.1.5 on 2025-04-09 12:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0017_remove_student_note_studentcourse_email_opened_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcourse',
            name='gen_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
