# Generated by Django 5.1.5 on 2025-04-12 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0018_studentcourse_gen_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentcourse',
            name='gen_time',
        ),
    ]
