# Generated by Django 5.1.5 on 2025-04-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0020_studentcourse_certificate_issued_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='alternate_phone',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='guardian_no',
            field=models.CharField(blank=True, db_index=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
    ]
