# Generated by Django 5.1.5 on 2025-05-26 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0021_alter_student_alternate_phone_alter_student_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentcourse',
            name='email_opened',
        ),
        migrations.RemoveField(
            model_name='studentcourse',
            name='email_opened_at',
        ),
        migrations.AddField(
            model_name='student',
            name='re_permission',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='studentcourse',
            name='marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentcourse',
            name='marks_update_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentnotes',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
