# Generated by Django 5.1.5 on 2025-06-07 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0022_remove_studentcourse_email_opened_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcourse',
            name='student_old_book_allotment',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Temp Block', 'Temp Block'), ('Restricted', 'Restricted')], default='Active', max_length=25, null=True),
        ),
    ]
