# Generated by Django 5.1.5 on 2025-06-24 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0023_studentcourse_student_old_book_allotment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcourse',
            name='student_exam_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
