# Generated by Django 5.1.5 on 2025-09-04 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0025_tags_studenttags'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentnotes',
            name='status_note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
