# Generated by Django 5.1.5 on 2025-09-04 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0026_studentnotes_status_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='tags',
            field=models.ManyToManyField(related_name='student_tags', through='Student.StudentTags', to='Student.tags'),
        ),
    ]
