# Generated by Django 5.1.5 on 2025-02-12 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Counsellor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='counsellor',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Leave', 'Leave'), ('Inactive', 'Inactive')], default='Active', max_length=10, null=True),
        ),
    ]
