# Generated by Django 5.1.5 on 2025-03-01 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Counsellor', '0004_alter_counsellor_counsellor_id_alter_counsellor_name_and_more'),
        ('nexus', '0013_customuser_first_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='counsellor',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nexus.location'),
        ),
    ]
