# Generated by Django 5.1.5 on 2025-02-05 05:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coordinator', '0001_initial'),
        ('Student', '0001_initial'),
        ('Trainer', '0001_initial'),
        ('nexus', '0002_coordinator_counsellor_course_location_timeslot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(max_length=15, unique=True)),
                ('status', models.CharField(blank=True, choices=[('Hold', 'Hold'), ('Running', 'Running'), ('Upcoming', 'Upcoming'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], default='Upcoming', max_length=10, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('mode', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], max_length=10)),
                ('language', models.CharField(choices=[('English', 'English'), ('Hindi', 'Hindi')], max_length=10)),
                ('preferred_week', models.CharField(choices=[('Weekdays', 'Weekdays'), ('Weekends', 'Weekends'), ('Both', 'Both')], default='Weekdays', max_length=10)),
                ('last_update_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('gen_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('batch_time', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nexus.timeslot')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nexus.course')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batches_created', to='Coordinator.coordinator')),
                ('last_update_coordinator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batches_update', to='Coordinator.coordinator')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nexus.location')),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Trainer.trainer')),
            ],
        ),
        migrations.CreateModel(
            name='BatchStudentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nexus.batch')),
                ('coordinator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Coordinator.coordinator')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.student')),
            ],
            options={
                'unique_together': {('batch', 'student')},
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=25)),
                ('book_stock', models.IntegerField()),
                ('last_update_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('gen_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nexus.course')),
                ('create_coordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_create', to='Coordinator.coordinator')),
                ('last_update_coordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_update', to='Coordinator.coordinator')),
            ],
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='coordinator',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='last_update_coordinator',
        ),
        migrations.DeleteModel(
            name='Counsellor',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='course',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='location',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='teamleader',
        ),
        migrations.AddField(
            model_name='batch',
            name='student',
            field=models.ManyToManyField(blank=True, through='nexus.BatchStudentAssignment', to='Student.student'),
        ),
        migrations.DeleteModel(
            name='Coordinator',
        ),
        migrations.DeleteModel(
            name='Trainer',
        ),
    ]
