# Generated by Django 5.1.5 on 2025-02-05 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexus', '0003_batch_batchstudentassignment_book_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
