# Generated by Django 5.1.5 on 2025-02-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexus', '0007_alter_batch_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='mode',
            field=models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline'), ('Hybrid', 'Hybrid')], max_length=10),
        ),
    ]
