# Generated by Django 5.1.5 on 2025-02-15 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexus', '0008_alter_batch_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nexus.timeslot'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nexus.location'),
        ),
    ]
