# Generated by Django 5.1.5 on 2025-02-18 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexus', '0009_alter_batch_batch_time_alter_batch_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch_id',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
