# Generated by Django 5.1.5 on 2025-02-25 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexus', '0010_alter_batch_batch_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='first_login',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('coordinator', 'Coordinator'), ('counsellor', 'Counsellor'), ('trainer', 'Trainer'), ('student', 'Student')], default='student', max_length=20),
        ),
    ]
