# Generated by Django 5.1.5 on 2025-02-25 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nexus', '0011_customuser_first_login_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='first_login',
        ),
    ]
