# Generated by Django 5.1.5 on 2025-03-01 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coordinator', '0004_alter_coordinator_coordinator_id_and_more'),
        ('nexus', '0013_customuser_first_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='batch_coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Coordinator.coordinator'),
        ),
    ]
