# Generated by Django 5.1.5 on 2025-03-24 10:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexus', '0015_otpverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchstudentassignment',
            name='last_update_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='batchstudentassignment',
            name='student_batch_status',
            field=models.CharField(blank=True, choices=[('In', 'In'), ('Out', 'Out')], default='In', max_length=10, null=True),
        ),
    ]
