# Generated by Django 5.1.5 on 2025-03-26 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexus', '0016_batchstudentassignment_last_update_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='special_time_slot',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Bootcamp', 'Bootcamp')], max_length=20, null=True),
        ),
    ]
