# Generated by Django 5.1.5 on 2025-03-27 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexus', '0016_batchstudentassignment_last_update_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='special_time_slot',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Special', 'Special')], default='Normal', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='week_type',
            field=models.CharField(choices=[('Weekdays', 'Weekdays'), ('Weekends', 'Weekends'), ('Both', 'Both')], default='Weekdays', max_length=10),
        ),
    ]
