# Generated by Django 5.1.5 on 2025-04-08 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexus', '0019_alter_timeslot_special_time_slot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_stock',
            new_name='stock',
        ),
        migrations.RemoveField(
            model_name='book',
            name='book_create_user',
        ),
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Not', 'Not')], default='Available', max_length=20),
        ),
        migrations.AddField(
            model_name='book',
            name='version',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
