# Generated by Django 5.1.5 on 2025-04-21 09:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexus', '0020_rename_book_stock_book_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='batch_create_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='batch',
            name='last_update_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
