# Generated by Django 5.1.5 on 2025-05-26 12:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0022_remove_studentcourse_email_opened_and_more'),
        ('Trainer', '0010_trainer_leave_end_date_trainer_leave_status_and_more'),
        ('nexus', '0021_batch_batch_create_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='batch_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='batchstudentassignment',
            name='add_in_batch_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='batchstudentassignment',
            name='add_in_batch_email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batchstudentassignment',
            name='batch_completed_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='batchstudentassignment',
            name='batch_completed_email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('text', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='announcement/')),
                ('gen_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('announcement_type', models.CharField(choices=[('Specific', 'Specific'), ('Overall', 'Overall')], default='Overall', max_length=10)),
                ('batch', models.ManyToManyField(blank=True, to='nexus.batch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('student', models.ManyToManyField(blank=True, to='Student.student')),
                ('trainer', models.ManyToManyField(blank=True, to='Trainer.trainer')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainer_name', models.CharField(blank=True, editable=False, max_length=50, null=True)),
                ('course_name', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('date', models.DateField()),
                ('gen_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('attendance', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], max_length=50)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nexus.batch')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nexus.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.student')),
                ('time_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nexus.timeslot')),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Trainer.trainer')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceWarningEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_opened', models.BooleanField(default=False)),
                ('email_send_date', models.DateTimeField(auto_now=True)),
                ('email_subject', models.CharField(blank=True, max_length=150, null=True)),
                ('gen_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('send_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ManyToManyField(blank=True, to='Student.student')),
            ],
        ),
        migrations.CreateModel(
            name='CancelBatchEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_opened', models.BooleanField(default=False)),
                ('email_send_date', models.DateTimeField(auto_now=True)),
                ('email_subject', models.CharField(blank=True, max_length=150, null=True)),
                ('gen_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('send_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ManyToManyField(blank=True, to='Student.student')),
            ],
        ),
        migrations.CreateModel(
            name='ComplateBatchEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_opened', models.BooleanField(default=False)),
                ('email_send_date', models.DateTimeField(auto_now=True)),
                ('email_subject', models.CharField(blank=True, max_length=150, null=True)),
                ('gen_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('send_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ManyToManyField(blank=True, to='Student.student')),
            ],
        ),
        migrations.CreateModel(
            name='CustomEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_opened', models.BooleanField(default=False)),
                ('email_send_date', models.DateTimeField(auto_now=True)),
                ('email_subject', models.CharField(blank=True, max_length=150, null=True)),
                ('gen_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('send_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ManyToManyField(blank=True, to='Student.student')),
            ],
        ),
        migrations.CreateModel(
            name='ExamAnnouncementEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_opened', models.BooleanField(default=False)),
                ('email_send_date', models.DateTimeField(auto_now=True)),
                ('email_subject', models.CharField(blank=True, max_length=150, null=True)),
                ('gen_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('send_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ManyToManyField(blank=True, to='Student.student')),
            ],
        ),
        migrations.CreateModel(
            name='StartBatchEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_opened', models.BooleanField(default=False)),
                ('email_send_date', models.DateTimeField(auto_now=True)),
                ('email_subject', models.CharField(blank=True, max_length=150, null=True)),
                ('gen_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('send_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ManyToManyField(blank=True, to='Student.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentBatchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(default='Batch Request', max_length=50)),
                ('request_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Cancelled', 'Cancelled')], default='Pending', max_length=50)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nexus.batch')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.student')),
            ],
        ),
        migrations.CreateModel(
            name='TerminationBatchEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_opened', models.BooleanField(default=False)),
                ('email_send_date', models.DateTimeField(auto_now=True)),
                ('email_subject', models.CharField(blank=True, max_length=150, null=True)),
                ('gen_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('send_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ManyToManyField(blank=True, to='Student.student')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('ticket_id', models.CharField(blank=True, editable=False, max_length=5, unique=True)),
                ('issue_type', models.CharField(choices=[('Book', 'Book'), ('Batch', 'Batch'), ('Certificate', 'Certificate'), ('Internet', 'Internet'), ('Unable to receive OTP', 'Unable to receive OTP'), ('Management (chairs , labs)', 'Management (chairs , labs)'), ('Fee', 'Fee'), ('Other', 'Other')], default='Other', max_length=50)),
                ('status', models.CharField(choices=[('Raise', 'Raise'), ('Open', 'Open'), ('Ongoing', 'Ongoing'), ('Closed', 'Closed')], default='Raise', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='Student.student')),
            ],
        ),
        migrations.CreateModel(
            name='TicketChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('student', 'student'), ('coordinator', 'coordinator'), ('admin', 'admin')], max_length=20)),
                ('message', models.TextField()),
                ('message_status', models.CharField(choices=[('Open', 'Open'), ('Not Open', 'Not Open')], default='Not Open', max_length=20)),
                ('gen_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('open_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='nexus.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='WelcomeEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_opened', models.BooleanField(default=False)),
                ('email_send_date', models.DateTimeField(auto_now=True)),
                ('email_subject', models.CharField(blank=True, max_length=150, null=True)),
                ('gen_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('send_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ManyToManyField(blank=True, to='Student.student')),
            ],
        ),
    ]
