# Generated by Django 5.1.5 on 2025-07-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexus', '0024_chatmessage_file_alter_batch_last_update_datetime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('user_agent', models.TextField()),
                ('blocked_at', models.DateTimeField(auto_now_add=True)),
                ('unblock_at', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Answered', 'Answered'), ('Your-Query', 'Your-Query'), ('Closed', 'Closed')], default='Raise', max_length=20),
        ),
    ]
