# Generated by Django 5.1.5 on 2025-09-04 06:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0027_student_tags'),
        ('nexus', '0025_blockedip_alter_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchstudentassignment',
            name='joined_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='batchstudentassignment',
            name='left_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='file_size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='forwarded_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forwarded_msgs', to='nexus.chatmessage'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='is_forwarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='nexus.chatmessage'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attendance',
            field=models.CharField(choices=[('Not Marked', 'Not Marked'), ('Present', 'Present'), ('Absent', 'Absent')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'batch', 'date')},
        ),
    ]
