# Generated by Django 5.1.5 on 2025-09-04 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nexus', '0026_batchstudentassignment_joined_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchstudentassignment',
            name='joined_on',
        ),
        migrations.RemoveField(
            model_name='batchstudentassignment',
            name='left_on',
        ),
    ]
