# Generated by Django 5.1.5 on 2025-09-07 08:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexus', '0027_remove_batchstudentassignment_joined_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchstudentassignment',
            name='joined_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='batchstudentassignment',
            name='left_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
