# Generated by Django 5.1.5 on 2025-02-08 10:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trainer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='gen_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='trainer',
            name='is_teamleader',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainer',
            name='languages',
            field=models.CharField(blank=True, choices=[('English', 'English'), ('Hindi', 'Hindi'), ('Both', 'Both')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='last_update_time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='trainer',
            name='last_update_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainer_update', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainer',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='trainer/profile_pics/'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Leave', 'Leave'), ('Inactive', 'Inactive')], default='Active', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='teamleader',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_teamleader': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to='Trainer.trainer'),
        ),
    ]
