# Generated by Django 5.1.5 on 2025-02-09 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trainer', '0002_trainer_gen_time_trainer_is_teamleader_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='experience',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
