# Generated by Django 5.1.5 on 2025-02-15 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coordinator', '0003_alter_coordinator_status'),
        ('Trainer', '0004_alter_trainer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Coordinator.coordinator'),
        ),
    ]
