# Generated by Django 5.1.5 on 2025-02-15 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trainer', '0005_alter_trainer_coordinator'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='status_change_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
