# Generated by Django 5.1.5 on 2025-02-25 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trainer', '0006_trainer_status_change_date'),
        ('nexus', '0011_customuser_first_login_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nexus.location'),
        ),
    ]
