# Generated by Django 5.1.5 on 2025-03-31 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trainer', '0008_alter_trainer_email_alter_trainer_phone'),
        ('nexus', '0019_alter_timeslot_special_time_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='timeslot',
            field=models.ManyToManyField(blank=True, to='nexus.timeslot'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='course',
            field=models.ManyToManyField(blank=True, to='nexus.course'),
        ),
    ]
