# Generated by Django 5.1.5 on 2025-05-26 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trainer', '0009_trainer_timeslot_alter_trainer_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='leave_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='leave_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='real_status',
            field=models.BooleanField(default=False),
        ),
    ]
