# Generated by Django 5.1.5 on 2025-06-07 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trainer', '0010_trainer_leave_end_date_trainer_leave_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='leave_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
