# Generated by Django 5.1.5 on 2025-06-24 07:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trainer', '0011_trainer_leave_start_date'),
        ('nexus', '0024_chatmessage_file_alter_batch_last_update_datetime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerBatchEndEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_opened', models.BooleanField(default=False)),
                ('email_send_date', models.DateTimeField(auto_now_add=True)),
                ('email_subject', models.CharField(blank=True, max_length=150, null=True)),
                ('gen_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('batch', models.ManyToManyField(blank=True, to='nexus.batch')),
                ('trainers', models.ManyToManyField(blank=True, to='Trainer.trainer')),
            ],
        ),
    ]
